### ISSUE TITLE
Issue with leapseconds-handling

### ISSUE THREAD

**Issue by rainerduffner** [reallyenglish/ansible-role-ntpd#24]
Hi,

can you make the leap-seconds file optional?
Or the fetching?

E.g. FreeBSD handles the leap-seconds file via its normal system-updates - no need to fetch it.

RHEL/CentOS don't seem to bother with a special ntp.conf statement about leap-seconds by default.

Don't know about Debian et.al.

Addionally, the download-URL is behind cloudflare and I would have to basically open the firewall up to all of the internet for this to work in most cases, here (which is not happening).

**Comment by trombik** [comment]
the branch `issue_24` should work for you.
